<?php
/**
 * MachtigingRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  P4NL_DATABASE_INTERFACE
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GPN.RegistrerenApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace P4NL_DATABASE_INTERFACE;

/**
 * MachtigingRequestTest Class Doc Comment
 *
 * @category    Class
 * @description MachtigingRequest
 * @package     P4NL_DATABASE_INTERFACE
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MachtigingRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MachtigingRequest"
     */
    public function testMachtigingRequest()
    {
    }

    /**
     * Test attribute "marketingcode"
     */
    public function testPropertyMarketingcode()
    {
    }

    /**
     * Test attribute "literatuurcode"
     */
    public function testPropertyLiteratuurcode()
    {
    }

    /**
     * Test attribute "initialen"
     */
    public function testPropertyInitialen()
    {
    }

    /**
     * Test attribute "voornaam"
     */
    public function testPropertyVoornaam()
    {
    }

    /**
     * Test attribute "tussenvoegsel"
     */
    public function testPropertyTussenvoegsel()
    {
    }

    /**
     * Test attribute "achternaam"
     */
    public function testPropertyAchternaam()
    {
    }

    /**
     * Test attribute "geslacht"
     */
    public function testPropertyGeslacht()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "registreer_email_niewsbrief"
     */
    public function testPropertyRegistreerEmailNiewsbrief()
    {
    }

    /**
     * Test attribute "guid"
     */
    public function testPropertyGuid()
    {
    }

    /**
     * Test attribute "geboortedatum"
     */
    public function testPropertyGeboortedatum()
    {
    }

    /**
     * Test attribute "telefoonnummer"
     */
    public function testPropertyTelefoonnummer()
    {
    }

    /**
     * Test attribute "mobielnummer"
     */
    public function testPropertyMobielnummer()
    {
    }

    /**
     * Test attribute "straat"
     */
    public function testPropertyStraat()
    {
    }

    /**
     * Test attribute "huisnummer"
     */
    public function testPropertyHuisnummer()
    {
    }

    /**
     * Test attribute "huisnummertoevoeging"
     */
    public function testPropertyHuisnummertoevoeging()
    {
    }

    /**
     * Test attribute "postcode"
     */
    public function testPropertyPostcode()
    {
    }

    /**
     * Test attribute "woonplaats"
     */
    public function testPropertyWoonplaats()
    {
    }

    /**
     * Test attribute "landcode"
     */
    public function testPropertyLandcode()
    {
    }

    /**
     * Test attribute "bedrag"
     */
    public function testPropertyBedrag()
    {
    }

    /**
     * Test attribute "rekeningnummer"
     */
    public function testPropertyRekeningnummer()
    {
    }

    /**
     * Test attribute "machtigingtype"
     */
    public function testPropertyMachtigingtype()
    {
    }

    /**
     * Test attribute "einddatum"
     */
    public function testPropertyEinddatum()
    {
    }

    /**
     * Test attribute "looptijd"
     */
    public function testPropertyLooptijd()
    {
    }

    /**
     * Test attribute "extra_informatie"
     */
    public function testPropertyExtraInformatie()
    {
    }

    /**
     * Test attribute "contact_guid"
     */
    public function testPropertyContactGuid()
    {
    }
}
