<?php
/**
 * PaymentRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  P4NL_DATABASE_INTERFACE
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GPN.RegistrerenApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace P4NL_DATABASE_INTERFACE;

/**
 * PaymentRequestTest Class Doc Comment
 *
 * @category    Class
 * @description PaymentRequest
 * @package     P4NL_DATABASE_INTERFACE
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PaymentRequest"
     */
    public function testPaymentRequest()
    {
    }

    /**
     * Test attribute "initials"
     */
    public function testPropertyInitials()
    {
    }

    /**
     * Test attribute "firstname"
     */
    public function testPropertyFirstname()
    {
    }

    /**
     * Test attribute "middlename"
     */
    public function testPropertyMiddlename()
    {
    }

    /**
     * Test attribute "lastname"
     */
    public function testPropertyLastname()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "birthday"
     */
    public function testPropertyBirthday()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "housenumber"
     */
    public function testPropertyHousenumber()
    {
    }

    /**
     * Test attribute "housenumber_addition"
     */
    public function testPropertyHousenumberAddition()
    {
    }

    /**
     * Test attribute "postcode"
     */
    public function testPropertyPostcode()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "phonenumber"
     */
    public function testPropertyPhonenumber()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }

    /**
     * Test attribute "issuers_bank"
     */
    public function testPropertyIssuersBank()
    {
    }

    /**
     * Test attribute "client_ip"
     */
    public function testPropertyClientIp()
    {
    }

    /**
     * Test attribute "client_user_agent"
     */
    public function testPropertyClientUserAgent()
    {
    }

    /**
     * Test attribute "return_url_success"
     */
    public function testPropertyReturnUrlSuccess()
    {
    }

    /**
     * Test attribute "return_url_cancel"
     */
    public function testPropertyReturnUrlCancel()
    {
    }

    /**
     * Test attribute "return_url_error"
     */
    public function testPropertyReturnUrlError()
    {
    }

    /**
     * Test attribute "return_url_reject"
     */
    public function testPropertyReturnUrlReject()
    {
    }

    /**
     * Test attribute "marketing_code"
     */
    public function testPropertyMarketingCode()
    {
    }

    /**
     * Test attribute "literature_code"
     */
    public function testPropertyLiteratureCode()
    {
    }

    /**
     * Test attribute "guid"
     */
    public function testPropertyGuid()
    {
    }

    /**
     * Test attribute "country_id"
     */
    public function testPropertyCountryId()
    {
    }

    /**
     * Test attribute "account_number"
     */
    public function testPropertyAccountNumber()
    {
    }

    /**
     * Test attribute "subscription_code"
     */
    public function testPropertySubscriptionCode()
    {
    }

    /**
     * Test attribute "subscription_end_date"
     */
    public function testPropertySubscriptionEndDate()
    {
    }

    /**
     * Test attribute "subscription_months"
     */
    public function testPropertySubscriptionMonths()
    {
    }

    /**
     * Test attribute "contact_guid"
     */
    public function testPropertyContactGuid()
    {
    }
}
