<?php
/**
 * PeriodiekSchenkenRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  P4NL_DATABASE_INTERFACE
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GPN.RegistrerenApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace P4NL_DATABASE_INTERFACE;

/**
 * PeriodiekSchenkenRequestTest Class Doc Comment
 *
 * @category    Class
 * @description PeriodiekSchenkenRequest
 * @package     P4NL_DATABASE_INTERFACE
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PeriodiekSchenkenRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PeriodiekSchenkenRequest"
     */
    public function testPeriodiekSchenkenRequest()
    {
    }

    /**
     * Test attribute "marketingcode"
     */
    public function testPropertyMarketingcode()
    {
    }

    /**
     * Test attribute "screen_id"
     */
    public function testPropertyScreenId()
    {
    }

    /**
     * Test attribute "bedrag"
     */
    public function testPropertyBedrag()
    {
    }

    /**
     * Test attribute "jaar"
     */
    public function testPropertyJaar()
    {
    }

    /**
     * Test attribute "geslacht"
     */
    public function testPropertyGeslacht()
    {
    }

    /**
     * Test attribute "initialen"
     */
    public function testPropertyInitialen()
    {
    }

    /**
     * Test attribute "voornamen"
     */
    public function testPropertyVoornamen()
    {
    }

    /**
     * Test attribute "tussenvoegsel"
     */
    public function testPropertyTussenvoegsel()
    {
    }

    /**
     * Test attribute "achternaam"
     */
    public function testPropertyAchternaam()
    {
    }

    /**
     * Test attribute "geboortedatum"
     */
    public function testPropertyGeboortedatum()
    {
    }

    /**
     * Test attribute "geboorteplaats"
     */
    public function testPropertyGeboorteplaats()
    {
    }

    /**
     * Test attribute "burgelijkestaat"
     */
    public function testPropertyBurgelijkestaat()
    {
    }

    /**
     * Test attribute "postcode"
     */
    public function testPropertyPostcode()
    {
    }

    /**
     * Test attribute "huisnummer"
     */
    public function testPropertyHuisnummer()
    {
    }

    /**
     * Test attribute "huisnummertoevoeging"
     */
    public function testPropertyHuisnummertoevoeging()
    {
    }

    /**
     * Test attribute "straat"
     */
    public function testPropertyStraat()
    {
    }

    /**
     * Test attribute "woonplaats"
     */
    public function testPropertyWoonplaats()
    {
    }

    /**
     * Test attribute "telefoonnummer"
     */
    public function testPropertyTelefoonnummer()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "rekeningnummer"
     */
    public function testPropertyRekeningnummer()
    {
    }

    /**
     * Test attribute "betalingstermijn"
     */
    public function testPropertyBetalingstermijn()
    {
    }

    /**
     * Test attribute "landcode"
     */
    public function testPropertyLandcode()
    {
    }

    /**
     * Test attribute "voornamen_partner"
     */
    public function testPropertyVoornamenPartner()
    {
    }

    /**
     * Test attribute "achternaam_partner"
     */
    public function testPropertyAchternaamPartner()
    {
    }

    /**
     * Test attribute "geboortedatum_partner"
     */
    public function testPropertyGeboortedatumPartner()
    {
    }

    /**
     * Test attribute "geboorteplaats_partner"
     */
    public function testPropertyGeboorteplaatsPartner()
    {
    }
}
