<?php
/**
 * RelatedTransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  P4NL_DATABASE_INTERFACE
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GPN.RegistrerenApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace P4NL_DATABASE_INTERFACE;

/**
 * RelatedTransactionTest Class Doc Comment
 *
 * @category    Class
 * @description RelatedTransaction
 * @package     P4NL_DATABASE_INTERFACE
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RelatedTransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RelatedTransaction"
     */
    public function testRelatedTransaction()
    {
    }

    /**
     * Test attribute "relation_type"
     */
    public function testPropertyRelationType()
    {
    }

    /**
     * Test attribute "related_transaction_key"
     */
    public function testPropertyRelatedTransactionKey()
    {
    }
}
