<?php
/**
 * TransactionStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  P4NL_DATABASE_INTERFACE
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GPN.RegistrerenApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace P4NL_DATABASE_INTERFACE;

/**
 * TransactionStatusTest Class Doc Comment
 *
 * @category    Class
 * @description TransactionStatus
 * @package     P4NL_DATABASE_INTERFACE
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TransactionStatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TransactionStatus"
     */
    public function testTransactionStatus()
    {
    }

    /**
     * Test attribute "key"
     */
    public function testPropertyKey()
    {
    }

    /**
     * Test attribute "invoice"
     */
    public function testPropertyInvoice()
    {
    }

    /**
     * Test attribute "service_code"
     */
    public function testPropertyServiceCode()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "is_test"
     */
    public function testPropertyIsTest()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "amount_debit"
     */
    public function testPropertyAmountDebit()
    {
    }

    /**
     * Test attribute "amount_credit"
     */
    public function testPropertyAmountCredit()
    {
    }

    /**
     * Test attribute "transaction_type"
     */
    public function testPropertyTransactionType()
    {
    }

    /**
     * Test attribute "services"
     */
    public function testPropertyServices()
    {
    }

    /**
     * Test attribute "custom_parameters"
     */
    public function testPropertyCustomParameters()
    {
    }

    /**
     * Test attribute "additional_parameters"
     */
    public function testPropertyAdditionalParameters()
    {
    }

    /**
     * Test attribute "mutation_type"
     */
    public function testPropertyMutationType()
    {
    }

    /**
     * Test attribute "related_transactions"
     */
    public function testPropertyRelatedTransactions()
    {
    }

    /**
     * Test attribute "is_cancelable"
     */
    public function testPropertyIsCancelable()
    {
    }

    /**
     * Test attribute "issuing_country"
     */
    public function testPropertyIssuingCountry()
    {
    }

    /**
     * Test attribute "start_recurrent"
     */
    public function testPropertyStartRecurrent()
    {
    }

    /**
     * Test attribute "recurring"
     */
    public function testPropertyRecurring()
    {
    }

    /**
     * Test attribute "customer_name"
     */
    public function testPropertyCustomerName()
    {
    }

    /**
     * Test attribute "payer_hash"
     */
    public function testPropertyPayerHash()
    {
    }

    /**
     * Test attribute "payment_key"
     */
    public function testPropertyPaymentKey()
    {
    }
}
