<?php
/**
 * RegisterApiTest
 * PHP version 5
 *
 * @category Class
 * @package  P4NL_DATABASE_INTERFACE
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GPN.RegistrerenApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace P4NL_DATABASE_INTERFACE;

use \P4NL_DATABASE_INTERFACE\Configuration;
use \P4NL_DATABASE_INTERFACE\ApiException;
use \P4NL_DATABASE_INTERFACE\ObjectSerializer;

/**
 * RegisterApiTest Class Doc Comment
 *
 * @category Class
 * @package  P4NL_DATABASE_INTERFACE
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RegisterApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for info
     *
     * To test if this API controller is running..
     *
     */
    public function testInfo()
    {
    }

    /**
     * Test case for registerEmail
     *
     * To register a participant for an email newsletters..
     *
     */
    public function testRegisterEmail()
    {
    }

    /**
     * Test case for registerInfoRequest
     *
     * To register an information request..
     *
     */
    public function testRegisterInfoRequest()
    {
    }

    /**
     * Test case for registerPeriodiekeSchenking
     *
     * To register an periodical donation request..
     *
     */
    public function testRegisterPeriodiekeSchenking()
    {
    }
}
