<?php
/**
 * InfoRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  P4NL_DATABASE_INTERFACE
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GPN.RegistrerenApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace P4NL_DATABASE_INTERFACE\Model;

use \ArrayAccess;
use \P4NL_DATABASE_INTERFACE\ObjectSerializer;

/**
 * InfoRequest Class Doc Comment
 *
 * @category Class
 * @package  P4NL_DATABASE_INTERFACE
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InfoRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'InfoRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'voornaam' => 'string',
        'geslacht' => 'string',
        'initialen' => 'string',
        'tussenvoegsel' => 'string',
        'achternaam' => 'string',
        'landcode' => 'string',
        'postcode' => 'string',
        'huisnummer' => 'string',
        'huisnummertoevoeging' => 'string',
        'straat' => 'string',
        'plaats' => 'string',
        'telefoonnummer' => 'string',
        'mobielnummer' => 'string',
        'email' => 'string',
        'marketingcode' => 'string',
        'requested_item_id' => 'int',
        'aantal' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'voornaam' => null,
        'geslacht' => null,
        'initialen' => null,
        'tussenvoegsel' => null,
        'achternaam' => null,
        'landcode' => null,
        'postcode' => null,
        'huisnummer' => null,
        'huisnummertoevoeging' => null,
        'straat' => null,
        'plaats' => null,
        'telefoonnummer' => null,
        'mobielnummer' => null,
        'email' => null,
        'marketingcode' => null,
        'requested_item_id' => 'int32',
        'aantal' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'voornaam' => 'voornaam',
        'geslacht' => 'geslacht',
        'initialen' => 'initialen',
        'tussenvoegsel' => 'tussenvoegsel',
        'achternaam' => 'achternaam',
        'landcode' => 'landcode',
        'postcode' => 'postcode',
        'huisnummer' => 'huisnummer',
        'huisnummertoevoeging' => 'huisnummertoevoeging',
        'straat' => 'straat',
        'plaats' => 'plaats',
        'telefoonnummer' => 'telefoonnummer',
        'mobielnummer' => 'mobielnummer',
        'email' => 'email',
        'marketingcode' => 'marketingcode',
        'requested_item_id' => 'requestedItemId',
        'aantal' => 'aantal'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'voornaam' => 'setVoornaam',
        'geslacht' => 'setGeslacht',
        'initialen' => 'setInitialen',
        'tussenvoegsel' => 'setTussenvoegsel',
        'achternaam' => 'setAchternaam',
        'landcode' => 'setLandcode',
        'postcode' => 'setPostcode',
        'huisnummer' => 'setHuisnummer',
        'huisnummertoevoeging' => 'setHuisnummertoevoeging',
        'straat' => 'setStraat',
        'plaats' => 'setPlaats',
        'telefoonnummer' => 'setTelefoonnummer',
        'mobielnummer' => 'setMobielnummer',
        'email' => 'setEmail',
        'marketingcode' => 'setMarketingcode',
        'requested_item_id' => 'setRequestedItemId',
        'aantal' => 'setAantal'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'voornaam' => 'getVoornaam',
        'geslacht' => 'getGeslacht',
        'initialen' => 'getInitialen',
        'tussenvoegsel' => 'getTussenvoegsel',
        'achternaam' => 'getAchternaam',
        'landcode' => 'getLandcode',
        'postcode' => 'getPostcode',
        'huisnummer' => 'getHuisnummer',
        'huisnummertoevoeging' => 'getHuisnummertoevoeging',
        'straat' => 'getStraat',
        'plaats' => 'getPlaats',
        'telefoonnummer' => 'getTelefoonnummer',
        'mobielnummer' => 'getMobielnummer',
        'email' => 'getEmail',
        'marketingcode' => 'getMarketingcode',
        'requested_item_id' => 'getRequestedItemId',
        'aantal' => 'getAantal'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['voornaam'] = isset($data['voornaam']) ? $data['voornaam'] : null;
        $this->container['geslacht'] = isset($data['geslacht']) ? $data['geslacht'] : null;
        $this->container['initialen'] = isset($data['initialen']) ? $data['initialen'] : null;
        $this->container['tussenvoegsel'] = isset($data['tussenvoegsel']) ? $data['tussenvoegsel'] : null;
        $this->container['achternaam'] = isset($data['achternaam']) ? $data['achternaam'] : null;
        $this->container['landcode'] = isset($data['landcode']) ? $data['landcode'] : null;
        $this->container['postcode'] = isset($data['postcode']) ? $data['postcode'] : null;
        $this->container['huisnummer'] = isset($data['huisnummer']) ? $data['huisnummer'] : null;
        $this->container['huisnummertoevoeging'] = isset($data['huisnummertoevoeging']) ? $data['huisnummertoevoeging'] : null;
        $this->container['straat'] = isset($data['straat']) ? $data['straat'] : null;
        $this->container['plaats'] = isset($data['plaats']) ? $data['plaats'] : null;
        $this->container['telefoonnummer'] = isset($data['telefoonnummer']) ? $data['telefoonnummer'] : null;
        $this->container['mobielnummer'] = isset($data['mobielnummer']) ? $data['mobielnummer'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['marketingcode'] = isset($data['marketingcode']) ? $data['marketingcode'] : null;
        $this->container['requested_item_id'] = isset($data['requested_item_id']) ? $data['requested_item_id'] : null;
        $this->container['aantal'] = isset($data['aantal']) ? $data['aantal'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['achternaam'] === null) {
            $invalidProperties[] = "'achternaam' can't be null";
        }
        if ($this->container['landcode'] === null) {
            $invalidProperties[] = "'landcode' can't be null";
        }
        if ($this->container['huisnummer'] === null) {
            $invalidProperties[] = "'huisnummer' can't be null";
        }
        if ($this->container['straat'] === null) {
            $invalidProperties[] = "'straat' can't be null";
        }
        if ($this->container['plaats'] === null) {
            $invalidProperties[] = "'plaats' can't be null";
        }
        if ($this->container['marketingcode'] === null) {
            $invalidProperties[] = "'marketingcode' can't be null";
        }
        if ($this->container['requested_item_id'] === null) {
            $invalidProperties[] = "'requested_item_id' can't be null";
        }
        if (($this->container['requested_item_id'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'requested_item_id', must be smaller than or equal to 2147483647.";
        }

        if (($this->container['requested_item_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'requested_item_id', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets voornaam
     *
     * @return string
     */
    public function getVoornaam()
    {
        return $this->container['voornaam'];
    }

    /**
     * Sets voornaam
     *
     * @param string $voornaam voornaam
     *
     * @return $this
     */
    public function setVoornaam($voornaam)
    {
        $this->container['voornaam'] = $voornaam;

        return $this;
    }

    /**
     * Gets geslacht
     *
     * @return string
     */
    public function getGeslacht()
    {
        return $this->container['geslacht'];
    }

    /**
     * Sets geslacht
     *
     * @param string $geslacht geslacht
     *
     * @return $this
     */
    public function setGeslacht($geslacht)
    {
        $this->container['geslacht'] = $geslacht;

        return $this;
    }

    /**
     * Gets initialen
     *
     * @return string
     */
    public function getInitialen()
    {
        return $this->container['initialen'];
    }

    /**
     * Sets initialen
     *
     * @param string $initialen initialen
     *
     * @return $this
     */
    public function setInitialen($initialen)
    {
        $this->container['initialen'] = $initialen;

        return $this;
    }

    /**
     * Gets tussenvoegsel
     *
     * @return string
     */
    public function getTussenvoegsel()
    {
        return $this->container['tussenvoegsel'];
    }

    /**
     * Sets tussenvoegsel
     *
     * @param string $tussenvoegsel tussenvoegsel
     *
     * @return $this
     */
    public function setTussenvoegsel($tussenvoegsel)
    {
        $this->container['tussenvoegsel'] = $tussenvoegsel;

        return $this;
    }

    /**
     * Gets achternaam
     *
     * @return string
     */
    public function getAchternaam()
    {
        return $this->container['achternaam'];
    }

    /**
     * Sets achternaam
     *
     * @param string $achternaam achternaam
     *
     * @return $this
     */
    public function setAchternaam($achternaam)
    {
        $this->container['achternaam'] = $achternaam;

        return $this;
    }

    /**
     * Gets landcode
     *
     * @return string
     */
    public function getLandcode()
    {
        return $this->container['landcode'];
    }

    /**
     * Sets landcode
     *
     * @param string $landcode landcode
     *
     * @return $this
     */
    public function setLandcode($landcode)
    {
        $this->container['landcode'] = $landcode;

        return $this;
    }

    /**
     * Gets postcode
     *
     * @return string
     */
    public function getPostcode()
    {
        return $this->container['postcode'];
    }

    /**
     * Sets postcode
     *
     * @param string $postcode postcode
     *
     * @return $this
     */
    public function setPostcode($postcode)
    {
        $this->container['postcode'] = $postcode;

        return $this;
    }

    /**
     * Gets huisnummer
     *
     * @return string
     */
    public function getHuisnummer()
    {
        return $this->container['huisnummer'];
    }

    /**
     * Sets huisnummer
     *
     * @param string $huisnummer huisnummer
     *
     * @return $this
     */
    public function setHuisnummer($huisnummer)
    {
        $this->container['huisnummer'] = $huisnummer;

        return $this;
    }

    /**
     * Gets huisnummertoevoeging
     *
     * @return string
     */
    public function getHuisnummertoevoeging()
    {
        return $this->container['huisnummertoevoeging'];
    }

    /**
     * Sets huisnummertoevoeging
     *
     * @param string $huisnummertoevoeging huisnummertoevoeging
     *
     * @return $this
     */
    public function setHuisnummertoevoeging($huisnummertoevoeging)
    {
        $this->container['huisnummertoevoeging'] = $huisnummertoevoeging;

        return $this;
    }

    /**
     * Gets straat
     *
     * @return string
     */
    public function getStraat()
    {
        return $this->container['straat'];
    }

    /**
     * Sets straat
     *
     * @param string $straat straat
     *
     * @return $this
     */
    public function setStraat($straat)
    {
        $this->container['straat'] = $straat;

        return $this;
    }

    /**
     * Gets plaats
     *
     * @return string
     */
    public function getPlaats()
    {
        return $this->container['plaats'];
    }

    /**
     * Sets plaats
     *
     * @param string $plaats plaats
     *
     * @return $this
     */
    public function setPlaats($plaats)
    {
        $this->container['plaats'] = $plaats;

        return $this;
    }

    /**
     * Gets telefoonnummer
     *
     * @return string
     */
    public function getTelefoonnummer()
    {
        return $this->container['telefoonnummer'];
    }

    /**
     * Sets telefoonnummer
     *
     * @param string $telefoonnummer telefoonnummer
     *
     * @return $this
     */
    public function setTelefoonnummer($telefoonnummer)
    {
        $this->container['telefoonnummer'] = $telefoonnummer;

        return $this;
    }

    /**
     * Gets mobielnummer
     *
     * @return string
     */
    public function getMobielnummer()
    {
        return $this->container['mobielnummer'];
    }

    /**
     * Sets mobielnummer
     *
     * @param string $mobielnummer mobielnummer
     *
     * @return $this
     */
    public function setMobielnummer($mobielnummer)
    {
        $this->container['mobielnummer'] = $mobielnummer;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email email
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets marketingcode
     *
     * @return string
     */
    public function getMarketingcode()
    {
        return $this->container['marketingcode'];
    }

    /**
     * Sets marketingcode
     *
     * @param string $marketingcode marketingcode
     *
     * @return $this
     */
    public function setMarketingcode($marketingcode)
    {
        $this->container['marketingcode'] = $marketingcode;

        return $this;
    }

    /**
     * Gets requested_item_id
     *
     * @return int
     */
    public function getRequestedItemId()
    {
        return $this->container['requested_item_id'];
    }

    /**
     * Sets requested_item_id
     *
     * @param int $requested_item_id requested_item_id
     *
     * @return $this
     */
    public function setRequestedItemId($requested_item_id)
    {

        if (($requested_item_id > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $requested_item_id when calling InfoRequest., must be smaller than or equal to 2147483647.');
        }
        if (($requested_item_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $requested_item_id when calling InfoRequest., must be bigger than or equal to 1.');
        }

        $this->container['requested_item_id'] = $requested_item_id;

        return $this;
    }

    /**
     * Gets aantal
     *
     * @return int
     */
    public function getAantal()
    {
        return $this->container['aantal'];
    }

    /**
     * Sets aantal
     *
     * @param int $aantal aantal
     *
     * @return $this
     */
    public function setAantal($aantal)
    {
        $this->container['aantal'] = $aantal;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


